version: '3'
services:
  agent:
    container_name: dd-agent
    image: "datadog/agent:latest"
    environment:
      - DD_SITE
      - DD_API_KEY
      - DD_HOSTNAME=bootcamp-lab
      - DD_TAGS="project:bootcamp"
      ## APM
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      ## LOGS
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE_LOGS=name:agent
      - DD_DOCKER_LABELS_AS_TAGS={"my.custom.label.env":"env","my.custom.label.team":"team","my.custom.label.app":"app"}
      ## LIVE PROCESSES
      - DD_PROCESS_AGENT_ENABLED=true
      ## DOGSTATSD
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - 8126:8126/tcp # for APM
      - 8125:8125/udp # for Dogstatsd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro # LIVE PROCESSES
  discounts:
    container_name: discounts
    environment:
      - FLASK_APP=discounts.py
      # - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST=db
      - POSTGRES_DB=spree_discounts
      - DD_SERVICE=discounts-service
      - DD_RUNTIME_METRICS_ENABLED=true #enable runtime metrics collection
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_VERSION=${DISCOUNTS_VER}
      - DD_ENV=dev
    image: discounts:${DISCOUNTS_VER}
    command: ["/bin/bash", "-c", "sleep 3 ; ddtrace-run flask run --port=${DISCOUNTS_PORT} --host=0.0.0.0"]
    ports:
      - "${DISCOUNTS_PORT}:${DISCOUNTS_PORT}"
      - "22"
    depends_on:
      - agent
      - db
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "discounts-service"}]'
      my.custom.label.team: "discounts"
      my.custom.label.app: "spree"
  store-frontend:
    container_name: store-frontend
    environment:
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_RUNTIME_METRICS_ENABLED=true #enable runtime metrics collection
      - DD_ENV=dev
      - DD_SERVICE=store-frontend
      - DD_VERSION=${STORE_VER}
      - RAILS_HIDE_STACKTRACE=false
      - ADS_PORT=${ADS_PORT}
      - DISCOUNTS_PORT=${DISCOUNTS_PORT}
      - ADS_ROUTE=${ADS_ROUTE}
      - DISCOUNTS_ROUTE=${DISCOUNTS_ROUTE}
    image: store-frontend:${STORE_VER}
    ports:
      - "3000:3000"
    depends_on:
      - agent
      - db
      - discounts
      - advertisements
    labels:
      com.datadoghq.ad.logs: '[{"source": "ruby", "service": "store-frontend"}]'
      my.custom.label.team: "web"
      my.custom.label.app: "spree"
  advertisements:
    container_name: ads
    environment:
      - FLASK_APP=ads.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST=db
      - POSTGRES_DB=spree_ads
      - DD_SERVICE=ads-service
      - DD_AGENT_HOST=agent
      - DD_LOGS_INJECTION=true
      - DD_PROFILING_ENABLED=true
      - DD_RUNTIME_METRICS_ENABLED=true
      - DD_VERSION=${ADS_VER}
      - DD_ENV=dev
    image: ads:${ADS_VER}
    command: ["/bin/bash", "-c", "sleep 3 ; ddtrace-run flask run --port=${ADS_PORT} --host=0.0.0.0"]
    ports:
      - "${ADS_PORT}:${ADS_PORT}"
    depends_on:
      - agent
      - db
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "ads-service"}]'
      my.custom.label.team: "ads"
      my.custom.label.app: "spree"
  db:
    container_name: postgres
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - DD_ENV=dev
    volumes: 
      - ../db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ../db/dd_monitor.sql:/docker-entrypoint-initdb.d/dd_monitor.sql
    labels:
      com.datadoghq.ad.check_names: '["postgres"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host":"%%host%%", "port":5432,"username":"datadog","password":"ddpassword"}]'
      com.datadoghq.ad.logs: '[{"source": "postgresql", "service": "postgres"}]'
      my.custom.label.team: "db"
      my.custom.label.app: "spree"
  nginx:
     container_name: nginx
     image: nginx:1.21.4
     restart: always
     environment:
       - DD_ENV=dev
     volumes:
       - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
       - ../nginx/nginx.conf:/etc/nginx/nginx.conf
     ports:
       - "8080:8080"
     depends_on:
       - store-frontend
     labels:
       com.datadoghq.ad.check_names: '["nginx"]'
       com.datadoghq.ad.init_configs: '[{}]'
       com.datadoghq.ad.instances: '[{"nginx_status_url": "http://%%host%%:8080/nginx_status/"}]'
       my.custom.label.team: "nginx"
       my.custom.label.app: "spree"
